### ISSUE TITLE
Not an issue, but trying to understand the purpse of this icon, for the other icon, it does jump to others place, but this icone just refresh

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/hb#15]
Not an issue, but trying to understand the purpose of this icon, for the other icon, it does jump to others place, but this icon just refresh the page, understand its name as page. so we can't find this icon on other page other than home page, so it only shows the total pages of a site? Thank you. 

![image](https://user-images.githubusercontent.com/120798996/235287541-2b864503-d37a-4c86-8b2c-abce28e02cfe.png)

**Comment by razonyang** [comment]
Yep, it just jumps to the homepage, since there isn't a page describe about this info so far, perhaps it would be better that removing the link of that icon.

**Comment by johnsmithodom** [comment]
Maybe we can move it to the end of the icon list, and rename it as about, which link to a page where describes the site and give a overall view?
