### ISSUE TITLE
Feature request, can we have password protected pages? Thank you.

### ISSUE THREAD

**Issue by mobilelifeful** [hbstack/hb#17]

**Comment by razonyang** [comment]
It's out of scope of theme/static site, we are unable to protect the pages, you may need to find the related docs of your platform, such as Netlify and Cloudflare pages.

**Comment by mobilelifeful** [comment]
was thinking we cloud have 
https://github.com/Li4n0/hugo_encryptor 
in hbstack.  Thank you anyway.

**Comment by razonyang** [comment]
Hmm, you're requesting a partial protection, sounds interesting, reopening it for tracking this request.

**Comment by johnsmithodom** [comment]
hi @razonyang , also like the idea,  can you please share any update on this feature ?  Thank you in advance.

**Comment by razonyang** [comment]
@johnsmithodom Haven't started yet, need to confirm whether if the license of [Hugo encrypt](https://github.com/Izumiko/hugo-encrypt/issues/17) is compatible with current theme (MIT).

**Comment by razonyang** [comment]
Done, see https://hugomods.com/en/docs/content/encrypt/ for details.
